--VIEW 1

SELECT DATE(SC.INCIDENT_DATE_TIME) AS Incident_Date,
CT.DESCRIPTION AS Reason_For_Call,
D.DESCRIPTION AS Disposition,
B.NEIGHBORHOOD AS Beat, COUNT(*) AS Total_Incidents
FROM SERVICE_cALLS SC 
INNER JOIN CALL_TYPES CT
    ON SC.CALL_TYPE = CT.CALL_TYPE
INNER JOIN DISPOSITIONS D 
    ON SC.DISPO_CODE = D.DISPO_CODE
INNER JOIN BEATS B ON SC.BEAT = B.BEAT
GROUP BY DATE(SC.INCIDENT_DATE_TIME), CT.DESCRIPTION, D.DESCRIPTION, B.NEIGHBORHOOD
ORDER BY 1 DESC
LIMIT 10;

--VIEW 2

SELECT DATE(SC.INCIDENT_DATE_TIME) AS Incident_Date,
B.NEIGHBORHOOD AS Beat, 
CT.DESCRIPTION AS Reason_For_Call,
D.DESCRIPTION AS Disposition,
COUNT(*) AS Total_Incidents
FROM SERVICE_cALLS SC 
INNER JOIN CALL_TYPES CT
    ON SC.CALL_TYPE = CT.CALL_TYPE
INNER JOIN DISPOSITIONS D 
    ON SC.DISPO_CODE = D.DISPO_CODE
INNER JOIN BEATS B ON SC.BEAT = B.BEAT
GROUP BY DATE(SC.INCIDENT_DATE_TIME), B.NEIGHBORHOOD, CT.DESCRIPTION, D.DESCRIPTION
ORDER BY 5 DESC
LIMIT 10;


#Views

#initiate dictionary
#Add VIEWS
CREATE VIEW `CallsPerDayByReasonDispositionBeat` (
        SELECT DATE(SC.INCIDENT_DATE_TIME) AS Incident_Date,
        CT.DESCRIPTION AS Reason_For_Call,
        D.DESCRIPTION AS Disposition,
        B.NEIGHBORHOOD AS Beat, COUNT(*) AS Total_Incidents
        FROM SERVICE_cALLS SC
        INNER JOIN CALL_TYPES CT
            ON SC.CALL_TYPE = CT.CALL_TYPE
        INNER JOIN DISPOSITIONS D
            ON SC.DISPO_CODE = D.DISPO_CODE
        INNER JOIN BEATS B ON SC.BEAT = B.BEAT
        GROUP BY DATE(SC.INCIDENT_DATE_TIME), CT.DESCRIPTION, D.DESCRIPTION, B.NEIGHBORHOOD 
    )
    
CREATE VIEW `CallsPerZipCode` (
        SELECT ZC.ZIPCODE, COUNT(*) AS CALLSPERZIPCODE 
        FROM SERVICE_CALLS SC INNER JOIN ZIPCODES ZC
        ON SC.INCIDENT_NUM = ZC.INCIDENT_NUM
        GROUP BY ZC.ZIPCODE
    )
    
CREATE VIEW `CallTypessPerZipCode` (
        SELECT ZC.ZIPCODE, COUNT(DISTINCT SC.CALL_TYPE) AS CALLTYPESSPERZIPCODE 
        FROM SERVICE_CALLS SC INNER JOIN ZIPCODES ZC
        ON SC.INCIDENT_NUM = ZC.INCIDENT_NUM
        GROUP BY ZC.ZIPCODE
    )
    
CREATE VIEW `CallsByBeats` (
        SELECT B.NEIGHBORHOOD AS Beat, COUNT(DISTINCT SC.INCIDENT_NUM) AS CALLSPERBEAT 
        FROM SERVICE_CALLS SC INNER JOIN BEATS B
        ON SC.BEAT = B.BEAT
        GROUP BY B.NEIGHBORHOOD
    )
    
CREATE VIEW `CallsByCallType` (
        SELECT CT.DESCRIPTION AS CALL_TYPE, COUNT(DISTINCT SC.INCIDENT_NUM) AS CALLSPERCALLTYPE 
        FROM SERVICE_CALLS SC INNER JOIN CALL_TYPE CT
        ON SC.CALL_TYPE = CT.CALL_TYPE
        GROUP BY CT.DESCRIPTION
    )
    
CREATE VIEW `CallsByDispositionCode` (
        SELECT D.DESCRIPTION AS DISPOSITION, COUNT(DISTINCT SC.INCIDENT_NUM) AS CALLSPERDISPOSITION 
        FROM SERVICE_CALLS SC INNER JOIN DISPOSITION D
        ON SC.DISPO_CODE = D.DISPO_CODE
        GROUP BY D.DESCRIPTION
    ) 